### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by fforres** [fforres/rebrand#12]
Routes

- /media
    - Links al resto de las rutas
- /media/noderscast   - 
- /media/eljavascripto
- /media/meetups

Esos ultimos 3, pienso en Galerias de videos de youtube, (hay algunas API Calls en https://github.com/fforres/in_plain_js/blob/master/netflix/js/models/youtube.js)

**Comment by Xabadu** [comment]
Agree. Creo que el formato debiese ser:
/media/:proyectId/
/events/:eventId/
