### ISSUE TITLE
Header Nav

### ISSUE THREAD

**Issue by fforres** [fforres/rebrand#4]
- Use http://bulma.io/
- Static to the top

**Comment by fforres** [comment]
So... Preact tiene un componente <Link/> para sus rutas... 
la pregunta es, usaremos Rutas? 
@Xabadu

**Comment by Xabadu** [comment]
Creo que si. Los details (events/media) al menos deberían ir en una ruta aparte, pero solo esos se me ocurren por ahora.

**Comment by fforres** [comment]
Me parece. voy a  crear algo responsive para cuando sea mobile 👍
