### ISSUE TITLE
Agregar un Linter

### ISSUE THREAD

**Issue by fforres** [fforres/rebrand#8]
Deberíamos?  cc @Xabadu 

Se que airbnb-default no funciona con la ultima version de eslint ... pero podíamos instalar el default 😄

**Comment by Xabadu** [comment]
Pense agregar uno en el #3, pero vi que ya trae. Hay una regla definida en el package y una dependencia instalada. Es de developit. (synacor). Sirve?

**Comment by fforres** [comment]
:o touché... no me habia fijado :p me silencio entonces xD
