### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Xabadu** [fforres/rebrand#9]

**Comment by Xabadu** [comment]
@fforres can i haz assets? (Logos): Meetup, NodeSchool y EventLoop.

**Comment by fforres** [comment]
You can, los subo mañana a 1era :)

**Comment by fforres** [comment]
:D https://drive.google.com/open?id=0B0-c8vrue2QqcHkwLTdiSmQxNDg

**Comment by Xabadu** [comment]
❤️
